spring:
  application:
    name: urlshortener
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
